# constants 

OCCUPATIONS_FILENAME = "top_10_occupations.txt"
OCCUPATIONS_HEADER = "TOP_OCCUPATIONS;NUMBER_CERTIFIED_APPLICATIONS;PERCENTAGE"

STATES_FILENAME = "top_10_states.txt"
STATES_HEADER = "TOP_STATES;NUMBER_CERTIFIED_APPLICATIONS;PERCENTAGE"
